/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AtivarContaRouteImport } from './routes/ativar-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppCoachRouteImport } from './routes/_app.coach'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AppGuiaIndexRouteImport } from './routes/_app.guia.index'
import { Route as AppGuiaSecaoRouteImport } from './routes/_app.guia.$secao'
import { Route as AppProtocoloIndexRouteImport } from './routes/_app.protocolo.index'
import { Route as AppRotinasIndexRouteImport } from './routes/_app.rotinas.index'
import { Route as AppRotinasSlugRouteImport } from './routes/_app.rotinas.$slug'
import { Route as AppProtocoloDiaDiaRouteImport } from './routes/_app.protocolo.dia.$dia'
import { Route as ApiPublicWebhooksCaktoRouteImport } from './routes/api/public/webhooks/cakto'
import { Route as AppProtocoloDiaDiaConcluidaRouteImport } from './routes/_app.protocolo.dia.$dia.concluida'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivarContaRoute = AtivarContaRouteImport.update({
  id: '/ativar-conta',
  path: '/ativar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AppGuiaIndexRoute = AppGuiaIndexRouteImport.update({
  id: '/guia/',
  path: '/guia/',
  getParentRoute: () => AppRoute,
} as any)
const AppGuiaSecaoRoute = AppGuiaSecaoRouteImport.update({
  id: '/guia/$secao',
  path: '/guia/$secao',
  getParentRoute: () => AppRoute,
} as any)
const AppProtocoloIndexRoute = AppProtocoloIndexRouteImport.update({
  id: '/protocolo/',
  path: '/protocolo/',
  getParentRoute: () => AppRoute,
} as any)
const AppRotinasIndexRoute = AppRotinasIndexRouteImport.update({
  id: '/rotinas/',
  path: '/rotinas/',
  getParentRoute: () => AppRoute,
} as any)
const AppRotinasSlugRoute = AppRotinasSlugRouteImport.update({
  id: '/rotinas/$slug',
  path: '/rotinas/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppProtocoloDiaDiaRoute = AppProtocoloDiaDiaRouteImport.update({
  id: '/protocolo/dia/$dia',
  path: '/protocolo/dia/$dia',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWebhooksCaktoRoute = ApiPublicWebhooksCaktoRouteImport.update({
  id: '/api/public/webhooks/cakto',
  path: '/api/public/webhooks/cakto',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProtocoloDiaDiaConcluidaRoute =
  AppProtocoloDiaDiaConcluidaRouteImport.update({
    id: '/concluida',
    path: '/concluida',
    getParentRoute: () => AppProtocoloDiaDiaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ativar-conta': typeof AtivarContaRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/coach': typeof AppCoachRoute
  '/perfil': typeof AppPerfilRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/guia/$secao': typeof AppGuiaSecaoRoute
  '/rotinas/$slug': typeof AppRotinasSlugRoute
  '/guia/': typeof AppGuiaIndexRoute
  '/protocolo/': typeof AppProtocoloIndexRoute
  '/rotinas/': typeof AppRotinasIndexRoute
  '/protocolo/dia/$dia': typeof AppProtocoloDiaDiaRouteWithChildren
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
  '/protocolo/dia/$dia/concluida': typeof AppProtocoloDiaDiaConcluidaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ativar-conta': typeof AtivarContaRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/coach': typeof AppCoachRoute
  '/perfil': typeof AppPerfilRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/guia/$secao': typeof AppGuiaSecaoRoute
  '/rotinas/$slug': typeof AppRotinasSlugRoute
  '/guia': typeof AppGuiaIndexRoute
  '/protocolo': typeof AppProtocoloIndexRoute
  '/rotinas': typeof AppRotinasIndexRoute
  '/protocolo/dia/$dia': typeof AppProtocoloDiaDiaRouteWithChildren
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
  '/protocolo/dia/$dia/concluida': typeof AppProtocoloDiaDiaConcluidaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/ativar-conta': typeof AtivarContaRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/guia/$secao': typeof AppGuiaSecaoRoute
  '/_app/rotinas/$slug': typeof AppRotinasSlugRoute
  '/_app/guia/': typeof AppGuiaIndexRoute
  '/_app/protocolo/': typeof AppProtocoloIndexRoute
  '/_app/rotinas/': typeof AppRotinasIndexRoute
  '/_app/protocolo/dia/$dia': typeof AppProtocoloDiaDiaRouteWithChildren
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
  '/_app/protocolo/dia/$dia/concluida': typeof AppProtocoloDiaDiaConcluidaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ativar-conta'
    | '/login'
    | '/onboarding'
    | '/coach'
    | '/perfil'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/emails'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/guia/$secao'
    | '/rotinas/$slug'
    | '/guia/'
    | '/protocolo/'
    | '/rotinas/'
    | '/protocolo/dia/$dia'
    | '/api/public/webhooks/cakto'
    | '/protocolo/dia/$dia/concluida'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ativar-conta'
    | '/login'
    | '/onboarding'
    | '/coach'
    | '/perfil'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/emails'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
    | '/guia/$secao'
    | '/rotinas/$slug'
    | '/guia'
    | '/protocolo'
    | '/rotinas'
    | '/protocolo/dia/$dia'
    | '/api/public/webhooks/cakto'
    | '/protocolo/dia/$dia/concluida'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/ativar-conta'
    | '/login'
    | '/onboarding'
    | '/_app/coach'
    | '/_app/perfil'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/emails'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/_app/guia/$secao'
    | '/_app/rotinas/$slug'
    | '/_app/guia/'
    | '/_app/protocolo/'
    | '/_app/rotinas/'
    | '/_app/protocolo/dia/$dia'
    | '/api/public/webhooks/cakto'
    | '/_app/protocolo/dia/$dia/concluida'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AtivarContaRoute: typeof AtivarContaRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiPublicWebhooksCaktoRoute: typeof ApiPublicWebhooksCaktoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativar-conta': {
      id: '/ativar-conta'
      path: '/ativar-conta'
      fullPath: '/ativar-conta'
      preLoaderRoute: typeof AtivarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/guia/': {
      id: '/_app/guia/'
      path: '/guia'
      fullPath: '/guia/'
      preLoaderRoute: typeof AppGuiaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guia/$secao': {
      id: '/_app/guia/$secao'
      path: '/guia/$secao'
      fullPath: '/guia/$secao'
      preLoaderRoute: typeof AppGuiaSecaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/protocolo/': {
      id: '/_app/protocolo/'
      path: '/protocolo'
      fullPath: '/protocolo/'
      preLoaderRoute: typeof AppProtocoloIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rotinas/': {
      id: '/_app/rotinas/'
      path: '/rotinas'
      fullPath: '/rotinas/'
      preLoaderRoute: typeof AppRotinasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rotinas/$slug': {
      id: '/_app/rotinas/$slug'
      path: '/rotinas/$slug'
      fullPath: '/rotinas/$slug'
      preLoaderRoute: typeof AppRotinasSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/protocolo/dia/$dia': {
      id: '/_app/protocolo/dia/$dia'
      path: '/protocolo/dia/$dia'
      fullPath: '/protocolo/dia/$dia'
      preLoaderRoute: typeof AppProtocoloDiaDiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/webhooks/cakto': {
      id: '/api/public/webhooks/cakto'
      path: '/api/public/webhooks/cakto'
      fullPath: '/api/public/webhooks/cakto'
      preLoaderRoute: typeof ApiPublicWebhooksCaktoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/protocolo/dia/$dia/concluida': {
      id: '/_app/protocolo/dia/$dia/concluida'
      path: '/concluida'
      fullPath: '/protocolo/dia/$dia/concluida'
      preLoaderRoute: typeof AppProtocoloDiaDiaConcluidaRouteImport
      parentRoute: typeof AppProtocoloDiaDiaRoute
    }
  }
}

interface AppProtocoloDiaDiaRouteChildren {
  AppProtocoloDiaDiaConcluidaRoute: typeof AppProtocoloDiaDiaConcluidaRoute
}

const AppProtocoloDiaDiaRouteChildren: AppProtocoloDiaDiaRouteChildren = {
  AppProtocoloDiaDiaConcluidaRoute: AppProtocoloDiaDiaConcluidaRoute,
}

const AppProtocoloDiaDiaRouteWithChildren =
  AppProtocoloDiaDiaRoute._addFileChildren(AppProtocoloDiaDiaRouteChildren)

interface AppRouteChildren {
  AppCoachRoute: typeof AppCoachRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppGuiaSecaoRoute: typeof AppGuiaSecaoRoute
  AppRotinasSlugRoute: typeof AppRotinasSlugRoute
  AppGuiaIndexRoute: typeof AppGuiaIndexRoute
  AppProtocoloIndexRoute: typeof AppProtocoloIndexRoute
  AppRotinasIndexRoute: typeof AppRotinasIndexRoute
  AppProtocoloDiaDiaRoute: typeof AppProtocoloDiaDiaRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppCoachRoute: AppCoachRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppGuiaSecaoRoute: AppGuiaSecaoRoute,
  AppRotinasSlugRoute: AppRotinasSlugRoute,
  AppGuiaIndexRoute: AppGuiaIndexRoute,
  AppProtocoloIndexRoute: AppProtocoloIndexRoute,
  AppRotinasIndexRoute: AppRotinasIndexRoute,
  AppProtocoloDiaDiaRoute: AppProtocoloDiaDiaRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AtivarContaRoute: AtivarContaRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiPublicWebhooksCaktoRoute: ApiPublicWebhooksCaktoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
